### ISSUE TITLE
Esecuzione di applicazioni Windows

### ISSUE THREAD

**Issue by acquleo** [antonioCoco/RunasCs#8]
Ciao,
Sto provando ad avvisare applicativi windows e ci sono riuscito.
Il problema è che questi vengono eseguiti in ambiente grafico ridotto.
Come posso avviare un modalità normale?
Poi tardi vedo di allegare degli screenshot.
Grazie mille

**Comment by antonioCoco** [comment]
Ciao,
credo che tu abbia malinterpretato lo scopo di questo tool.
Ti invito a rileggere il readme.

**Comment by acquleo** [comment]
Scusami non so se ho interpretato male.
Dobbiamo implementare un sistema di autenticazione in un ambiente Kerberos/active directory
L'utente inserisce la credenziali in una applicazione dedicata e vengono avviate altre applicazioni che a questo punto accedono con la credenziale dell'utente che si è loggato.
Ho provato sia create process with logon che with token utilizzando il token restituito dalla funzione loginuser.
La differenza tra le due versioni è che la prima (with logon) funziona correttamente e l'applicazione window viene eseguita con l'utente utilizzando  impersonation, l'aspetto grafico è completo.
Mentre utilizzando with token, l'applicazione Windows viene avviata in modalità grafica ridotta.
Mi chiedevo solamente quale poteva essere la differenza tra le due funzioni.

Grazie mille
Leonardo
